DROP TABLE IF EXISTS PUBLIC.PRICES;

CREATE TABLE PUBLIC.PRICES
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID   INT            NOT NULL,
    START_DATE TIMESTAMP      NOT NULL,
    END_DATE   TIMESTAMP      NOT NULL,
    PRICE_LIST INT            NOT NULL,
    PRODUCT_ID INT            NOT NULL,
    PRIORITY   INT            NOT NULL,
    PRICE      DECIMAL(10, 2) NOT NULL,
    CURR       VARCHAR(3)     NOT NULL
);
