openapi: 3.0.0
info:
  title: Inditex Prices API
  version: "1.0"
  description: API to retrieve current price of products
paths:
  /api/v1/prices/product/{productId}/brand/{brandId}:
    get:
      operationId: getPriceByProductAndBrand
      summary: Get price for a given product and brand
      description: Retrieves the applicable price for a product under a brand.
      tags:
        - PricesV1
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: brandId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: applyDate
          in: query
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Price found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceResponseDto'
        '404':
          description: Price not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
components:
  schemas:
    PriceResponseDto:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        brandId:
          type: integer
          format: int64
        priceList:
          type: integer
        startDateTime:
          type: string
          format: date-time
          x-java-type: java.time.LocalDateTime
        endDateTime:
          type: string
          format: date-time
          x-java-type: java.time.LocalDateTime
        price:
          type: number
          x-java-type: java.math.BigDecimal
      required:
        - productId
        - brandId
        - priceList
        - startDateTime
        - endDateTime
        - price
    ErrorResponseDto:
      type: object
      properties:
        key:
          type: string
        message:
          type: string
        dateTime:
          type: string
          format: date-time
          x-java-type: java.time.LocalDateTime
      required:
        - key
        - message
        - dateTime

